2025-10-27 01:08:53,401 - ERROR - Некорректный ID
Traceback (most recent call last):
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 259, in run
    print(self.delete_candidate())
          ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 223, in delete_candidate
    raise ValueError("Некорректный ID")
ValueError: Некорректный ID
2025-10-27 01:11:04,648 - ERROR - Некорректный ID
Traceback (most recent call last):
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 259, in run
    print(self.delete_candidate())
          ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 224, in delete_candidate
    valid_id = validate_id(id)
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/validate.py", line 42, in validate_id
    raise ValueError("Некорректный ID")
ValueError: Некорректный ID
2025-10-27 01:14:12,896 - ERROR - Некорректная почта
Traceback (most recent call last):
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 249, in run
    self.add_candidate()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 151, in add_candidate
    email = validate_email(email)
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/validate.py", line 29, in validate_email
    raise ValueError("Некорректная почта")
ValueError: Некорректная почта
2025-10-27 01:15:54,687 - ERROR - Некорректный возраст
Traceback (most recent call last):
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 249, in run
    self.add_candidate()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 149, in add_candidate
    age = validate_age(age)
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/validate.py", line 23, in validate_age
    raise ValueError("Некорректный возраст")
ValueError: Некорректный возраст
2025-10-27 01:22:26,237 - ERROR - Некорректное действие
Traceback (most recent call last):
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 257, in run
    print(self.edit_candidate())
          ~~~~~~~~~~~~~~~~~~~^^
  File "/home/oleg/Рабочий стол/для перевода v2.0.0/app/models.py", line 200, in edit_candidate
    raise ValueError("Некорректное действие")
ValueError: Некорректное действие
